services:
  superapp-apec:
    container_name: superapp-apec
    image: meta-link
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "127.0.0.1:3012:3012"

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3012"]
      interval: 30s
      timeout: 5s
      retries: 3

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
